### ISSUE TITLE
major changes PR

### ISSUE THREAD

**Issue by vkhatri** [guilhem-cookbooks/twemproxy#1]
hello there! is this repository still under development? i have made some changes to the cookbook and would like to submit a PR.

changes:
- add source base installation
- re-org recipes
- source base installation service runs with non root user
- add recipe to setup a non root user
- add all daemon arguments/options to /etc/default/twemproxy.override
- add log file support
- add different common directories
- source based installation support for more that one version
- add package/source version control
- add ulimits for non root service user, ignore if user is root (root is default for package install)
- add configurable apt repository attributes
- add packages dependencies recipe
- service notification must be restart
- add conditional service restart notification for config files update
- add daemon arguments attributes

**Comment by guilhem** [comment]
Yes under development and waiting for PR. :)

Can you just do some separate PR for each different features?

**Comment by vkhatri** [comment]
unfortunately i have a single PR, i do not think i can break it into individual PR in github.

but, let me know if i can do something to ease the merge :)
